# Generated by Django 6.0.3 on 2026-03-22 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(default='Ludhiana', max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('pa', 'Punjabi')], default='pa', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Farm', max_length=100)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(max_length=150)),
                ('soil_type', models.CharField(choices=[('loamy', 'Loamy'), ('sandy', 'Sandy Loam'), ('clay', 'Clay'), ('alluvial', 'Alluvial')], default='alluvial', max_length=20)),
                ('crops', models.CharField(help_text='Comma-separated crop names', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farmers.farmerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/')),
                ('detected_label', models.CharField(max_length=200)),
                ('confidence_pct', models.FloatField()),
                ('advice', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('risk_analysis', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='farmers.farmerprofile')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='farmers.farmerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
