# Generated by Django 6.0.3 on 2026-03-22 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('cause', models.CharField(choices=[('flood', 'Flood / Waterlogging'), ('drought', 'Drought / Water Shortage'), ('hailstorm', 'Hailstorm'), ('frost', 'Frost / Cold Wave'), ('fire', 'Fire'), ('pest', 'Pest / Disease Outbreak'), ('unseasonal_rain', 'Unseasonal Rain'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('partial', 'Partial (25–50% loss)'), ('major', 'Major (50–75% loss)'), ('total', 'Total (>75% loss)')], max_length=10)),
                ('affected_acres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('schemes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmers.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='farmers.farmerprofile')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
